name: myproject

services:
  db:
    #platform: linux/x86_64
    container_name: mysql-${COMPOSE_PROJECT_NAME}
    hostname: mysql-${COMPOSE_PROJECT_NAME}
    ports:
      - "0:3306"
    networks:
      - local

  wordpress:
    container_name: wordpress-${COMPOSE_PROJECT_NAME}
    build: .
    environment:
      WORDPRESS_DB_HOST: mysql-${COMPOSE_PROJECT_NAME}
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`dev.${COMPOSE_PROJECT_NAME}.docker`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=Host(`dev.${COMPOSE_PROJECT_NAME}.docker`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
    ports: !override []
    networks:
      - local
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${COMPOSE_PROJECT_NAME}
    #restart: unless-stopped
    restart: no
    ports:
      - "0:80"
    environment:
      PMA_HOST: mysql-${COMPOSE_PROJECT_NAME}
      PMA_USER: wordpress
      PMA_DATABASE: wordpress
      PMA_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    depends_on:
      - db
    networks:
      - web

  maildev:
    image: 'maildev/maildev'
    container_name: maildev-${COMPOSE_PROJECT_NAME}
    ports:
      - "0:1080"
    networks:
      - local

networks:
  local:
    external: true